{
 "title": "Client Framerate and Round Trip Time",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "database", "query": "show databases" },
   {
    "name": "Model",
    "query": "show tag values on $database from framerate with key = \"MODEL\""
   },
   {
    "name": "ConnectionType",
    "query": "show tag values from framerate with key = \"CONNECTYPE\""
   },
   {
    "name": "Server",
    "query": "show tag values from framerate with key = \"SERVERURL\""
   }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 }, "content": "\n\n" },
  { "title": "Throughput", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 } },
  { "title": "Location", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Interval Frames Per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"INTERVALFPS\") FROM \"framerate\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall  Frames Per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"OVERALLFPS\") FROM \"framerate\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Interval Round Trip Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"INTERVALRTT\") FROM \"roundtriptime\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Round Trip Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"OVERALLRTT\") FROM \"roundtriptime\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"LAT\"  FROM \"location\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"LNG\"  FROM \"location\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Rates",
   "type": "graph",
   "description": "Shows long term and short term frames per second at the client",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Frames Per Second" }
   ],
   "targets": [
    {
     "alias": "Interval FPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT mean(\"INTERVALFPS\") FROM \"framerate\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTERVALFPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Overall FPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT mean(\"OVERALLFPS\") FROM \"framerate\" WHERE  (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OVERALLFPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Round Trip Times",
   "type": "graph",
   "description": "Shows long term and short term average  round trip at the client",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Round Trip Time (ms)" }
   ],
   "targets": [
    {
     "alias": "Interval RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "roundtriptime",
     "query": "SELECT mean(\"INTERVALRTT\") FROM \"roundtriptime\" WHERE  (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTERVALRTT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Overall RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "roundtriptime",
     "query": "SELECT mean(\"OVERALLRTT\") FROM \"roundtriptime\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OVERALLRTT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "location",
     "query": "SELECT distinct(\"LAT\") AS \"metric\" FROM \"location\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY \"latitude\", \"longitude\"",
     "select": [
      [
       { "params": [ "LAT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT type,description FROM $database.autogen.events WHERE $timeFilter ORDER BY time desc LIMIT 100",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}