---
- name: Create SSH directory
  file:
    path: "{{ ansible_env.HOME }}/{{ k8s_directory }}/.ssh"
    state: directory

- name: Generate an OpenSSH keypair
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/{{ k8s_directory }}/.ssh/id_rsa"
    comment: "{{ ansible_user }}@{{ ansible_host }}"

- name: Register SSH Public Key
  slurp:
    src: "{{ ansible_env.HOME }}/{{ k8s_directory }}/.ssh/id_rsa.pub"
  register: rke_ssh_key

- name: Add rke public SSH key to authorized keys list
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ rke_ssh_key['content'] | b64decode }}"
