default_indices = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 173, 174, 175, 176, 177, 178, 179, 180, 181, 183, 184, 185, 186, 187, 189, 190, 191, 192, 193, 194, 
                        195, 196, 197, 198, 203, 204, 205, 206, 207, 211, 214]

default_y_idx = 210

default_icols = ['VBIC_dirty_frames_per_second', 'VBIC_fbc_rate', 'VBIC_frames_per_second', 'VBIC_poll_rate', 'VBIC_received_bytes', 'VBIC_total_dirty_frames', 'VBIC_total_fbc', 
                 'VBIC_total_frames', 'VBIC_total_poll', 'VBIC_transmitted_bytes', 'VBIC_transmitted_packets', 'VBSC_cumulative_received_bytes_over_tcp', 
                 'VBSC_cumulative_received_bytes_over_udp', 'VBSC_cumulative_transmitted_bytes_over_tcp', 'VBSC_cumulative_transmitted_bytes_over_udp', 
                 'VBSC_estimated_bandwidth_uplink_', 'VBSC_instantaneous_received_bytes_over_tcp', 'VBSC_instantaneous_received_bytes_over_udp', 
                 'VBSC_instantaneous_transmitted_bytes_over_tcp', 'VBSC_instantaneous_transmitted_bytes_over_udp', 'VBSC_jitter_uplink_', 'VBSC_packet_loss_uplink_', 
                 'VBSC_received_bytes', 'VBSC_received_packets', 'VBSC_rtt', 'VBSC_transmitted_bytes', 'VBSC_transmitted_packets', 'logicaldisk_c_avg_disk_bytes_read', 
                 'logicaldisk_c_avg_disk_bytes_write', 'logicaldisk_c_avg_disk_queue_length', 'logicaldisk_c_avg_disk_sec_read', 'logicaldisk_c_avg_disk_sec_write', 
                 'logicaldisk_c_disk_read_bytes_sec', 'logicaldisk_c_disk_reads_sec', 'logicaldisk_c_disk_write_bytes_sec', 'logicaldisk_c_disk_writes_sec', 
                 'logicaldisk_harddiskvolume1_avg_disk_bytes_read', 'logicaldisk_harddiskvolume1_avg_disk_bytes_write', 
                 'logicaldisk_harddiskvolume1_avg_disk_queue_length', 'logicaldisk_harddiskvolume1_avg_disk_sec_read', 'logicaldisk_harddiskvolume1_avg_disk_sec_write', 
                 'logicaldisk_harddiskvolume1_disk_read_bytes_sec', 'logicaldisk_harddiskvolume1_disk_reads_sec', 'logicaldisk_harddiskvolume1_disk_write_bytes_sec', 
                 'logicaldisk_harddiskvolume1_disk_writes_sec', 'logicaldisk_harddiskvolume3_avg_disk_bytes_read', 'logicaldisk_harddiskvolume3_avg_disk_bytes_write', 
                 'logicaldisk_harddiskvolume3_avg_disk_queue_length', 'logicaldisk_harddiskvolume3_avg_disk_sec_read', 'logicaldisk_harddiskvolume3_avg_disk_sec_write', 
                 'logicaldisk_harddiskvolume3_disk_read_bytes_sec', 'logicaldisk_harddiskvolume3_disk_reads_sec', 'logicaldisk_harddiskvolume3_disk_write_bytes_sec', 
                 'logicaldisk_harddiskvolume3_disk_writes_sec', 'logicaldisk_total_avg_disk_bytes_read', 'logicaldisk_total_avg_disk_bytes_write', 
                 'logicaldisk_total_avg_disk_queue_length', 'logicaldisk_total_avg_disk_sec_read', 'logicaldisk_total_avg_disk_sec_write', 'logicaldisk_total_disk_read_bytes_sec', 
                 'logicaldisk_total_disk_reads_sec', 'logicaldisk_total_disk_write_bytes_sec', 'logicaldisk_total_disk_writes_sec', 'memory_available_bytes', 'memory_cache_bytes', 
                 'memory_cache_faults_sec', 'memory_committed_bytes', 'memory_page_faults_sec', 'memory_pages_sec', 'memory_pool_nonpaged_bytes', 'memory_pool_paged_bytes', 
                 'network_interface_vmxnet3_ethernet_adapter_bytes_received_sec', 'network_interface_vmxnet3_ethernet_adapter_bytes_sent_sec', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__available_memory_mb', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__bus_usage', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__core_clock_mhz', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__fb_usage', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__gpu_memory_usage', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__gpu_usage', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__memory_clock_mhz', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__total_memory_mb', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_decoder_usage', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_encoder_average_fps', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_encoder_average_latency_ms_', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_encoder_sessions', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_encoder_usage', 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__video_usage', 
                 'nvidia_gpu_0_grid_p40-2q_id-1_nvapi_id-512__virtual_memory_mb', 'processor_0__c1_time', 'processor_0__c2_time', 'processor_0__c3_time', 'processor_0__dpc_time', 
                 'processor_0__idle_time', 'processor_0__interrupt_time', 'processor_0__privileged_time', 'processor_0__processor_time', 'processor_0__user_time', 
                 'processor_0_c1_transitions_sec', 'processor_0_c2_transitions_sec', 'processor_0_c3_transitions_sec', 'processor_0_dpc_rate', 'processor_0_dpcs_queued_sec', 
                 'processor_0_interrupts_sec', 'processor_1__c1_time', 'processor_1__c2_time', 'processor_1__c3_time', 'processor_1__dpc_time', 'processor_1__idle_time', 
                 'processor_1__interrupt_time', 'processor_1__privileged_time', 'processor_1__processor_time', 'processor_1__user_time', 'processor_1_c1_transitions_sec', 
                 'processor_1_c2_transitions_sec', 'processor_1_c3_transitions_sec', 'processor_1_dpc_rate', 'processor_1_dpcs_queued_sec', 'processor_1_interrupts_sec', 
                 'processor_2__c1_time', 'processor_2__c2_time', 'processor_2__c3_time', 'processor_2__dpc_time', 'processor_2__idle_time', 'processor_2__interrupt_time', 
                 'processor_2__privileged_time', 'processor_2__processor_time', 'processor_2__user_time', 'processor_2_c1_transitions_sec', 'processor_2_c2_transitions_sec', 
                 'processor_2_c3_transitions_sec', 'processor_2_dpc_rate', 'processor_2_dpcs_queued_sec', 'processor_2_interrupts_sec', 'processor_3__c1_time', 
                 'processor_3__c2_time', 'processor_3__c3_time', 'processor_3__dpc_time', 'processor_3__idle_time', 'processor_3__interrupt_time', 'processor_3__privileged_time', 
                 'processor_3__processor_time', 'processor_3__user_time', 'processor_3_c1_transitions_sec', 'processor_3_c2_transitions_sec', 'processor_3_c3_transitions_sec', 
                 'processor_3_dpc_rate', 'processor_3_dpcs_queued_sec', 'processor_3_interrupts_sec', 'processor_total__c1_time', 'processor_total__c2_time', 
                 'processor_total__c3_time', 'processor_total__dpc_time', 'processor_total__idle_time', 'processor_total__interrupt_time', 'processor_total__privileged_time', 
                 'processor_total__processor_time', 'processor_total__user_time', 'processor_total_c1_transitions_sec', 'processor_total_c2_transitions_sec', 
                 'processor_total_c3_transitions_sec', 'processor_total_dpc_rate', 'processor_total_dpcs_queued_sec', 'processor_total_interrupts_sec', 'system_context_switches_sec', 
                 'system_processes', 'system_processor_queue_length', 'system_threads', 'MULTIPLIER', 'RATE', 'RTT_encmax', 'COUNTER_capture', 'CRAVG', 'CRFPS', 'DURATION_capture', 
                 'FPS_encmax', 'FRAMES_capture', 'COUNTER_desktop', 'DRAVG', 'DRFPS', 'DURATION_desktop', 'FRAMES_desktop', 'CLIENT', 'ENCAVG', 'ENCMAX', 'INFO_encmax', 'LASTFRAME', 
                 'MAPAVG', 'MAPMAX', 'SCHEDAVG', 'SCHEDMAX', 'ACTSTATECHANGE', 'MAXFPS', 'MAXRTT', 'RTT_fbchange', 'SOCKETQUEUEFPS', 'VNCENCODE', 'seqlen', 'on_advantedge']