---
- name: Download rke binary for {{ ansible_distribution }}
  become: yes
  get_url:
    url: https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_{{ operating_system }}-{{ arch }}
    dest: /usr/local/bin/rke
    mode: '0755'

- name: Download kubectl binary for {{ ansible_distribution }}
  become: yes
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/{{ operating_system }}/{{ arch }}/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Download helm binary for {{ ansible_distribution }}
  unarchive:
    src: https://get.helm.sh/helm-{{ helm_version }}-{{ operating_system }}-{{ arch }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy helm binary file to executable path
  become: yes
  copy:
    src: /tmp/{{ operating_system }}-{{ arch }}/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes
