---
- name: Install pip package
  when: ansible_distribution != "MacOSX"
  become: yes
  apt:
    update_cache: yes
    name: python3-pip

- name: Install docker python package
  become: yes
  pip:
    name: docker

- name: Install kubernetes and crypto python packages
  pip:
    name:
      - kubernetes
      - cryptography
      - pyopenssl

