---
- name: Install Ingress Nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    chart_version: "{{ ingress_nginx_chart_version }}"
    create_namespace: true
    values:
      controller:
        extraArgs:
          enable-ssl-passthrough: "true"
        ingressClassResource:
          default: "true"
