---
all:
  # Update your VM or bare-metal IP address
  hosts: 128.2.209.111
  # hosts: 127.0.0.1
  vars:
    ansible_user: jblake1
    arch: amd64
    domainName: magma.local
    magma_namespace: magma
    # directory path setup
    recipe_home: /home/jblake1/git/PyEdgeSim/ansible
    helm_local: "{{ recipe_home }}/helm/charts"
    secrets_local: "{{ recipe_home }}/secrets"
    files_local: "{{ recipe_home }}/files" 	
    tmp_local: "{{ recipe_home }}/tmp"
    bin_local: "{{ recipe_home }}/bin"
    logs_local: "{{ recipe_home }}/logs"
    
    # ssh key for all hosts
    ansible_ssh_private_key_file: "/home/jblake1/.ssh/jblake1-azure-02.pem"

