{
 "title": "Client Framerate and Round Trip Time",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "database", "query": "show databases" },
   {
    "name": "Model",
    "query": "show tag values on $database from allmeasure with key = \"MODEL\""
   },
   {
    "name": "ConnectionType",
    "query": "show tag values on $database from allmeasure with key = \"CONNECTYPE\""
   },
   {
    "name": "Server",
    "query": "show tag values  on $database from allmeasure with key = \"SERVERURL\""
   },
   { "name": "ScenarioDataSource", "query": "influxdb" },
   { "name": "ScenarioDB", "query": "show databases" },
   {
    "name": "src",
    "query": "show tag values on $ScenarioDB from network with key = \"src\""
   },
   {
    "name": "dest",
    "query": "show tag values on $ScenarioDB from network with key = \"dest\""
   }
  ]
 },
 "panels": [
  { "title": "FRAME RATE", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 }, "options": { "content": "\n\n" } },
  { "title": "ROUND TRIP TIME", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 } },
  { "title": "LOCATION", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Interval Frames Per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"INTERVALFPS\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Session Average  Frames Per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"OVERALLFPS\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Interval Round Trip Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"INTERVALRTT\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\"  WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Session Average Round Trip Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"OVERALLRTT\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"LAT\"  FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"LNG\"  FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Rates",
   "type": "graph",
   "description": "Shows long term and short term frames per second at the client",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Frames Per Second" }
   ],
   "targets": [
    {
     "alias": "Interval FPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT mean(\"INTERVALFPS\") FROM $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTERVALFPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Session Average  FPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT mean(\"OVERALLFPS\") FROM $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OVERALLFPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Round Trip Times",
   "type": "graph",
   "description": "Shows long term and short term average  round trip at the client",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Round Trip Time (ms)" }
   ],
   "targets": [
    {
     "alias": "Interval RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "roundtriptime",
     "query": "SELECT mean(\"INTERVALRTT\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTERVALRTT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Session Average RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "roundtriptime",
     "query": "SELECT mean(\"OVERALLRTT\") FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/ AND \"SERVERURL\" =~ /^$Server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OVERALLRTT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" }
     ],
     "measurement": "location",
     "query": "SELECT distinct(\"LAT\") AS \"metric\" FROM  $database.DefaultRetentionPolicy.\"allmeasure\" WHERE (\"MODEL\" =~ /^$Model$/ AND \"CONNECTYPE\" =~ /^$ConnectionType$/) AND $timeFilter GROUP BY \"latitude\", \"longitude\"",
     "select": [
      [
       { "params": [ "LAT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "graph",
   "description": "Shows long term and short term frames per second at the client",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT mean(\"lat\") FROM $ScenarioDB.autogen.network WHERE (\"src\" =~ /^$src$/ AND \"dest\" =~ /^$dest$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "INTERVALFPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT type,description FROM  $ScenarioDB.autogen.network WHERE $timeFilter ORDER BY time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT type,description FROM $ScenarioDB.autogen.events WHERE $timeFilter ORDER BY time desc LIMIT 100",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brought to you by:",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "options": {
    "content": "<p align=\"center\">\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n<img src=\"https://www.cmu.edu/brand/brand-guidelines/images/wordmarksquare-red-600x600.png\" alt=\"Carnegie Mellon Logo\" width=\"280\">\n<img src=\"https://www.openedgecomputing.org/content/images/2019/03/logo-small.png\u0000\" alt=\"Carnegie Mellon Logo\" width=\"280\"></p>\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n<img src=\"https://s3.amazonaws.com/files.interdigital.com/55bd0288af0b0930ba599bd0c4b7ca38/resources/img/id_logo_new.png\", width=\"560\">\n\n\n\n\n\n\n"
   }
  }
 ]
}